base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: true
  wait_timeout: 600
  pool: 25
  username: root
  password: 1234
  host: localhost
  port: 3306
  database: meetiao

development:
  <<: *base

test:
  <<: *base

production:
  <<: *base